# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

container:
  image: 'erlang:22.3'

steps:
- script: rebar3 tar
  displayName: 'Compiling into a tar'

- publish: _build/default/rel/dmdbserver/dmdbserver-0.1.0.tar.gz
  artifact: tar
  displayName: 'Publish tar package artifact'
